sudo: required
services: 
  - docker

before_install:
  - docker build -t abhishek-kumar-code/docker-react-travisci -f Dockerfile.dev .

script: 
  - docker run abhishek-kumar-code/docker-react-travisci npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react-travisci"
  env: "DockerReactTravisci-env"
  bucket_name: "elasticbeanstalk-us-east-1-309335768510"
  bucket_path: "docker-react-travisci"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"