sudo: required
services: 
  - docker

before_install:
  - docker build -t abhishek-kumar-code/docker-react-travisci -f Dockerfile.dev .

script: 
  - docker run abhishek-kumar-code/docker-react-travisci npm run test -- --coverage